/*
 * OV2640 camera (DVP parallel interface). Captures JPEG frames into PSRAM for
 * the MJPEG stream. XCLK is generated by LEDC timer 1 / channel 6 so it does
 * not collide with the motor PWM channels on LEDC timer 0.
 */

#ifndef FALCON_CAMERA_H_
#define FALCON_CAMERA_H_

#include "esp_err.h"

/* Initialize the sensor. Returns ESP_OK if a frame source is available. */
esp_err_t camera_init(void);

/* True once camera_init succeeded. */
bool camera_ok(void);

#endif /* FALCON_CAMERA_H_ */
