#include "camera.h"
#include "esp_camera.h"
#include "esp_log.h"

static const char *TAG = "camera";
static bool s_ok;

/* DVP pin mapping from the confirmed Falcon Core pinout.
 * esp_camera pin_d0..d7 correspond to OV2640 data lines D2..D9. */
#define CAM_PIN_PWDN    -1    /* tied low in hardware  */
#define CAM_PIN_RESET   -1    /* tied high in hardware */
#define CAM_PIN_XCLK    39
#define CAM_PIN_SIOD    1     /* SCCB SDA */
#define CAM_PIN_SIOC    2     /* SCCB SCL */
#define CAM_PIN_D7      40    /* D9 */
#define CAM_PIN_D6      9     /* D8 */
#define CAM_PIN_D5      10    /* D7 */
#define CAM_PIN_D4      11    /* D6 */
#define CAM_PIN_D3      13    /* D5 */
#define CAM_PIN_D2      21    /* D4 */
#define CAM_PIN_D1      14    /* D3 */
#define CAM_PIN_D0      12    /* D2 */
#define CAM_PIN_VSYNC   42
#define CAM_PIN_HREF    41
#define CAM_PIN_PCLK    38

esp_err_t camera_init(void)
{
    camera_config_t config = {
        .pin_pwdn = CAM_PIN_PWDN,
        .pin_reset = CAM_PIN_RESET,
        .pin_xclk = CAM_PIN_XCLK,
        .pin_sccb_sda = CAM_PIN_SIOD,
        .pin_sccb_scl = CAM_PIN_SIOC,
        .pin_d7 = CAM_PIN_D7,
        .pin_d6 = CAM_PIN_D6,
        .pin_d5 = CAM_PIN_D5,
        .pin_d4 = CAM_PIN_D4,
        .pin_d3 = CAM_PIN_D3,
        .pin_d2 = CAM_PIN_D2,
        .pin_d1 = CAM_PIN_D1,
        .pin_d0 = CAM_PIN_D0,
        .pin_vsync = CAM_PIN_VSYNC,
        .pin_href = CAM_PIN_HREF,
        .pin_pclk = CAM_PIN_PCLK,

        .xclk_freq_hz = 20000000,
        /* On the ESP32-S3 the camera XCLK is generated by LEDC; keep it off
         * LEDC timer 0 / channels 0-5 used by the motor PWM. */
        .ledc_timer = LEDC_TIMER_1,
        .ledc_channel = LEDC_CHANNEL_6,

        .pixel_format = PIXFORMAT_JPEG,
        .frame_size = FRAMESIZE_VGA,     /* 640x480, 4:3 */
        .jpeg_quality = 12,              /* 0-63, lower = higher quality */
        .fb_count = 2,
        .fb_location = CAMERA_FB_IN_PSRAM,
        .grab_mode = CAMERA_GRAB_WHEN_EMPTY,
    };

    esp_err_t err = esp_camera_init(&config);
    if (err != ESP_OK) {
        ESP_LOGE(TAG, "esp_camera_init failed: 0x%x", err);
        s_ok = false;
        return err;
    }

    sensor_t *s = esp_camera_sensor_get();
    if (s) {
        s->set_vflip(s, 0);
        s->set_hmirror(s, 0);
    }
    s_ok = true;
    ESP_LOGI(TAG, "OV2640 ready (VGA JPEG)");
    return ESP_OK;
}

bool camera_ok(void)
{
    return s_ok;
}
