idf_component_register(
    SRCS
        "main.c"
        "state.c"
        "led.c"
        "wifi.c"
        "motors.c"
        "battery.c"
        "sensors.c"
        "fusion.c"
        "magcal.c"
        "camera.c"
        "server.c"
    INCLUDE_DIRS "."
    REQUIRES
        esp_driver_i2c
        esp_driver_ledc
        esp_driver_gpio
        esp_adc
        esp_timer
        esp_wifi
        esp_event
        esp_netif
        nvs_flash
        esp_http_server
        bmi270
        vl53l5cx
)
